(()=>{
  const LIMITS={normal:2.3,watch:4.5,alert:7.1};
  const PULLEY_POINTS=new Map([[2,'Pulley Primary - L'],[3,'Pulley Primary - R'],[7,'Pulley Secondery - L'],[8,'Pulley Secondery - R'],[12,'Pulley Take-up - L'],[13,'Pulley Take-up - R'],[17,'Pulley Tail - L'],[18,'Pulley Tail - R']]);
  const GEARBOX_POINTS=new Map([[22,'DRIVE UNIT 1 - Gear Box'],[28,'DRIVE UNIT 2 - Gear Box'],[34,'DRIVE UNIT 3 - Gear Box'],[40,'DRIVE UNIT 4 - Gear Box'],[46,'DRIVE UNIT 5 (Tail) - Gear Box']]);
  const num=v=>{const s=String(v??'').trim().replace(',','.');if(!s)return null;const n=Number(s);return Number.isFinite(n)?n:null};
  function records(){try{return typeof filteredDashboardRecords==='function'?filteredDashboardRecords():[]}catch(e){return []}}
  function isDrive(r){const d=r?.data||{};const k=String(d.checklist_type||r.checklist_type||'').toLowerCase();const name=String(d.checklist_name||r.checklist_name||'').toLowerCase();return !k||k==='drive_station'||k.includes('drive')||name.includes('drive station')}
  function points(){const a=[];GEARBOX_POINTS.forEach((l,n)=>a.push([`gearbox|||${n}`,l]));PULLEY_POINTS.forEach((l,n)=>a.push([`pulley|||${n}`,l]));return a}
  function rebuild(preferred){const s=document.getElementById('vibrationPoint');if(!s)return;const old=preferred||s.dataset.vibSelected||s.value;s.innerHTML=points().map(([v,l])=>`<option value="${v}">${l}</option>`).join('');if(points().some(x=>x[0]===old))s.value=old;s.dataset.vibSelected=s.value}
  function bind(){const s=document.getElementById('vibrationPoint');if(!s||s.dataset.vibBound==='2')return;s.onchange=null;s.removeAttribute('onchange');s.addEventListener('change',function(e){this.dataset.vibSelected=this.value;e.stopImmediatePropagation();draw(this.value,false)});s.dataset.vibBound='2';const d=document.getElementById('vibrationDisplayMode');if(d){d.innerHTML='<option value="selected">จุดที่เลือก</option>';d.value='selected';d.onchange=null;d.removeAttribute('onchange')}}
  function configureInputs(){document.querySelectorAll('tr.item-row').forEach(row=>{const n=Number(row.dataset.no||row.cells?.[0]?.textContent||0);if(GEARBOX_POINTS.has(n))return;const input=row.querySelector(`input[name="vibration_${n}"]`),td=input?.closest('td')||row.querySelector('.vibration-na');if(PULLEY_POINTS.has(n)){if(!input&&td){td.className='';td.innerHTML=`<input class="text-input vibration-input" type="number" inputmode="decimal" step="0.01" min="0" name="vibration_${n}" placeholder="0.00">`}}else if(input&&td){td.className='vibration-na';td.innerHTML='<span>—</span>'}})}
  function latest(kind,n){const m=new Map();records().forEach(r=>{if(!isDrive(r))return;const d=r.data||{},date=d.inspection_date||'';if(!date)return;let val;if(kind==='gearbox'){const legacy=num(d[`vibration_${n}`]);val={input:num(d[`vibration_input_${n}`])??legacy,output:num(d[`vibration_output_${n}`])};if(val.input==null&&val.output==null)return}else{const v=num(d[`vibration_${n}`]);if(v==null)return;val={single:v}}const stamp=String(r.updated_at||r.created_at||r.saved_at||'');const old=m.get(date);if(!old||stamp>=old.stamp)m.set(date,{stamp,...val})});return m}
  const status=v=>v==null?'-':v<LIMITS.normal?'Normal':v<LIMITS.watch?'Watch':v<LIMITS.alert?'Alert':'Danger';
  function draw(preferred,rebuildOptions=true){if(rebuildOptions)rebuild(preferred);bind();configureInputs();reference();const s=document.getElementById('vibrationPoint'),c=document.getElementById('vibrationTrendChart');if(!s||!c||!s.value)return;if(preferred&&[...s.options].some(o=>o.value===preferred))s.value=preferred;s.dataset.vibSelected=s.value;const [kind,ns]=s.value.split('|||'),n=Number(ns),by=latest(kind,n),dates=[...by.keys()].sort(),iv=kind==='gearbox'?dates.map(d=>by.get(d).input):[],ov=kind==='gearbox'?dates.map(d=>by.get(d).output):[],sv=kind==='pulley'?dates.map(d=>by.get(d).single):[];canvas(c,dates,kind,iv,ov,sv);summary(kind,iv,ov,sv);const note=c.closest('.condition-card')?.querySelector('.condition-note');if(note)note.textContent=kind==='gearbox'?'Gearbox: แสดง Input และ Output จากช่อง Vibration ใน Checklist':`${PULLEY_POINTS.get(n)}: อ่านค่าจากช่อง Vibration ของ Pulley ใน Checklist`}
  function canvas(c,dates,kind,iv,ov,sv){const xctx=c.getContext('2d'),r=c.getBoundingClientRect(),q=devicePixelRatio||1,w=Math.max(360,r.width||700),h=Math.max(285,r.height||285);c.width=w*q;c.height=h*q;xctx.setTransform(q,0,0,q,0,0);xctx.clearRect(0,0,w,h);const series=kind==='gearbox'?[['Input',iv,'#236c93'],['Output',ov,'#d47a23']]:[['Vibration',sv,'#236c93']],all=series.flatMap(x=>x[1]).filter(Number.isFinite);if(!dates.length||!all.length){xctx.fillStyle='#667784';xctx.font='13px system-ui';xctx.textAlign='center';xctx.fillText('ยังไม่มีข้อมูล Vibration ที่บันทึกสำหรับจุดนี้',w/2,h/2);return}const p={l:55,r:24,t:35,b:48},pw=w-p.l-p.r,ph=h-p.t-p.b,max=Math.max(8,Math.ceil((Math.max(...all,7.1)+.5)*2)/2),Y=v=>p.t+ph*(1-v/max),X=i=>dates.length>1?p.l+pw*i/(dates.length-1):p.l+pw/2;[[0,2.3,'rgba(25,135,84,.07)'],[2.3,4.5,'rgba(255,193,7,.08)'],[4.5,7.1,'rgba(255,126,0,.07)'],[7.1,max,'rgba(220,53,69,.06)']].forEach(([a,b,col])=>{xctx.fillStyle=col;xctx.fillRect(p.l,Y(b),pw,Y(a)-Y(b))});for(let i=0;i<=4;i++){const v=max-max*i/4,py=Y(v);xctx.strokeStyle='#d7e0e6';xctx.beginPath();xctx.moveTo(p.l,py);xctx.lineTo(w-p.r,py);xctx.stroke();xctx.fillStyle='#667784';xctx.font='10px system-ui';xctx.textAlign='right';xctx.fillText(v.toFixed(1),p.l-7,py+3)}series.forEach(([name,vals,col])=>{xctx.strokeStyle=col;xctx.fillStyle=col;xctx.lineWidth=2.4;xctx.beginPath();let started=false;vals.forEach((v,i)=>{if(!Number.isFinite(v))return;const xx=X(i),yy=Y(v);started?xctx.lineTo(xx,yy):(xctx.moveTo(xx,yy),started=true)});xctx.stroke();vals.forEach((v,i)=>{if(!Number.isFinite(v))return;const xx=X(i),yy=Y(v);xctx.beginPath();xctx.arc(xx,yy,4,0,Math.PI*2);xctx.fill();xctx.font='700 10px system-ui';xctx.textAlign='center';xctx.fillText(v.toFixed(2),xx,Math.max(p.t+9,yy-9))})});xctx.fillStyle='#667784';xctx.font='10px system-ui';xctx.textAlign='center';dates.forEach((d,i)=>{if(i%Math.max(1,Math.ceil(dates.length/8))===0||i===dates.length-1)xctx.fillText(String(d).slice(8,10)+'/'+String(d).slice(5,7),X(i),h-p.b+20)});if(kind==='gearbox'){xctx.textAlign='left';xctx.font='600 11px system-ui';xctx.fillStyle='#236c93';xctx.fillText('● Input',p.l,p.t-15);xctx.fillStyle='#d47a23';xctx.fillText('● Output',p.l+70,p.t-15)}}
  function summary(kind,iv,ov,sv){const a=document.getElementById('vibChecked'),box=a?.closest('.condition-summary');if(!box)return;if(kind==='gearbox'){const li=[...iv].reverse().find(Number.isFinite),lo=[...ov].reverse().find(Number.isFinite),all=[...iv,...ov].filter(Number.isFinite);box.innerHTML=`<span>ล่าสุด Input: <b>${li==null?'-':li.toFixed(2)+' mm/s'}</b></span><span>ล่าสุด Output: <b>${lo==null?'-':lo.toFixed(2)+' mm/s'}</b></span><span>สูงสุด: <b>${all.length?Math.max(...all).toFixed(2)+' mm/s':'-'}</b></span><span>สถานะ: <b>${status(all.length?Math.max(li??-Infinity,lo??-Infinity):null)}</b></span><span>จำนวนค่า: <b id="vibChecked">${all.length}</b></span>`}else{const all=sv.filter(Number.isFinite),last=[...sv].reverse().find(Number.isFinite);box.innerHTML=`<span>ล่าสุด: <b>${last==null?'-':last.toFixed(2)+' mm/s'}</b></span><span>ต่ำสุด: <b>${all.length?Math.min(...all).toFixed(2)+' mm/s':'-'}</b></span><span>สูงสุด: <b>${all.length?Math.max(...all).toFixed(2)+' mm/s':'-'}</b></span><span>สถานะ: <b>${status(last)}</b></span><span>จำนวนค่า: <b id="vibChecked">${all.length}</b></span>`}}
  function reference(){const c=document.getElementById('vibrationTrendChart'),card=c?.closest('.condition-card');if(!card||card.querySelector('.vib-standard-reference'))return;const n=document.createElement('div');n.className='vib-standard-reference';n.innerHTML='<b>Screening reference:</b> Normal &lt;2.3, Watch 2.3–&lt;4.5, Alert 4.5–&lt;7.1, Danger ≥7.1 mm/s RMS <span>(เกณฑ์คัดกรองเบื้องต้น)</span>';c.closest('.chart-wrap')?.before(n)}
  const st=document.createElement('style');st.textContent='.vibration-na{text-align:center!important;color:#9aa8b2!important;font-weight:700}.vib-standard-reference{margin:7px 0 4px;padding:7px 9px;border:1px solid #d6e0e6;border-radius:8px;background:#f7fafc;font-size:10px;color:#526674}#vibrationTrendChart{min-height:285px}';document.head.appendChild(st);
  const old=window.renderConditionTrends;if(typeof old==='function'){const wrap=function(...args){const keep=document.getElementById('vibrationPoint')?.dataset.vibSelected||'';let r;try{r=old.apply(this,args)}catch(e){if(!/vib(Latest|Min|Max|Checked|OK|NG|Rate)/.test(String(e?.message||e)))console.warn('base condition trend failed',e)}setTimeout(()=>draw(keep,true),0);return r};window.renderConditionTrends=wrap;try{renderConditionTrends=wrap}catch(e){}}
  document.addEventListener('change',e=>{if(['dashChecklist','dashMachine','dashOperator','dashDateFrom','dashDateTo'].includes(e.target?.id))setTimeout(()=>draw(document.getElementById('vibrationPoint')?.dataset.vibSelected||'',true),20)});
  const tb=document.getElementById('checklistBody');if(tb)new MutationObserver(()=>setTimeout(configureInputs,0)).observe(tb,{childList:true,subtree:true});
  setTimeout(()=>draw('',true),350);setTimeout(()=>draw(document.getElementById('vibrationPoint')?.dataset.vibSelected||'',true),1000);
})();