(()=>{
  const LIMITS={normal:2.3,watch:4.5,alert:7.1};
  const PULLEY_POINTS=new Map([[2,'Pulley Primary - L'],[3,'Pulley Primary - R'],[7,'Pulley Secondery - L'],[8,'Pulley Secondery - R'],[12,'Pulley Take-up - L'],[13,'Pulley Take-up - R'],[17,'Pulley Tail - L'],[18,'Pulley Tail - R']]);
  const GEARBOX_POINTS=new Map([[22,'DRIVE UNIT 1 - Gear Box'],[28,'DRIVE UNIT 2 - Gear Box'],[34,'DRIVE UNIT 3 - Gear Box'],[40,'DRIVE UNIT 4 - Gear Box'],[46,'DRIVE UNIT 5 (Tail) - Gear Box']]);
  const num=v=>{const s=String(v??'').trim().replace(',','.');if(!s||/^(OK|NG)$/i.test(s))return null;const n=Number(s);return Number.isFinite(n)?n:null};
  function records(){try{return typeof filteredDashboardRecords==='function'?filteredDashboardRecords():[]}catch(e){return []}}
  function isDrive(r){const d=r?.data||{};const k=String(d.checklist_type||r.checklist_type||'').toLowerCase();const name=String(d.checklist_name||r.checklist_name||'').toLowerCase();return !k||k==='drive_station'||k.includes('drive')||name.includes('drive station')}
  function hidePointControls(){const c=document.getElementById('vibrationTrendChart'),card=c?.closest('.condition-card');if(!card)return;const filter=card.querySelector('.condition-filter');if(filter)filter.style.display='none'}
  function configureInputs(){document.querySelectorAll('tr.item-row').forEach(row=>{const n=Number(row.dataset.no||row.cells?.[0]?.textContent||0);if(GEARBOX_POINTS.has(n))return;const input=row.querySelector(`input[name="vibration_${n}"]`),td=input?.closest('td')||row.querySelector('.vibration-na');if(PULLEY_POINTS.has(n)){if(!input&&td){td.className='';td.innerHTML=`<input class="text-input vibration-input" type="number" inputmode="decimal" step="0.01" min="0" name="vibration_${n}" placeholder="0.00">`}}else if(input&&td){td.className='vibration-na';td.innerHTML='<span>—</span>'}})}
  function recordValues(r){const d=r?.data||{},vals=[];GEARBOX_POINTS.forEach((label,n)=>{const legacy=num(d[`vibration_${n}`]),input=num(d[`vibration_input_${n}`])??legacy,output=num(d[`vibration_output_${n}`]);if(input!=null)vals.push({label:`${label} Input`,value:input});if(output!=null)vals.push({label:`${label} Output`,value:output})});PULLEY_POINTS.forEach((label,n)=>{const value=num(d[`vibration_${n}`]);if(value!=null)vals.push({label,value})});return vals}
  function byDate(){const m=new Map();records().forEach(r=>{if(!isDrive(r))return;const d=r.data||{},date=d.inspection_date||'';if(!date)return;const vals=recordValues(r);if(!vals.length)return;if(!m.has(date))m.set(date,[]);m.get(date).push(...vals)});return m}
  const status=v=>v==null?'-':v<LIMITS.normal?'Normal':v<LIMITS.watch?'Watch':v<LIMITS.alert?'Alert':'Danger';
  function draw(){hidePointControls();configureInputs();reference();const c=document.getElementById('vibrationTrendChart');if(!c)return;const grouped=byDate(),dates=[...grouped.keys()].sort(),maxVals=dates.map(d=>Math.max(...grouped.get(d).map(x=>x.value))),avgVals=dates.map(d=>grouped.get(d).reduce((s,x)=>s+x.value,0)/grouped.get(d).length),counts=dates.map(d=>grouped.get(d).length);canvas(c,dates,maxVals,avgVals);summary(dates,maxVals,avgVals,counts);const note=c.closest('.condition-card')?.querySelector('.condition-note');if(note)note.textContent='ภาพรวม: แสดงค่าสูงสุดและค่าเฉลี่ยจากทุกจุด Vibration ที่บันทึกไว้ใน Checklist'}
  function canvas(c,dates,maxVals,avgVals){const ctx=c.getContext('2d'),r=c.getBoundingClientRect(),q=devicePixelRatio||1,w=Math.max(360,r.width||700),h=Math.max(285,r.height||285);c.width=w*q;c.height=h*q;ctx.setTransform(q,0,0,q,0,0);ctx.clearRect(0,0,w,h);const series=[['สูงสุด',maxVals,'#236c93'],['เฉลี่ย',avgVals,'#d47a23']],all=series.flatMap(x=>x[1]).filter(Number.isFinite);if(!dates.length||!all.length){ctx.fillStyle='#667784';ctx.font='13px system-ui';ctx.textAlign='center';ctx.fillText('ยังไม่มีข้อมูล Vibration ที่บันทึก',w/2,h/2);return}const p={l:55,r:24,t:35,b:48},pw=w-p.l-p.r,ph=h-p.t-p.b,max=Math.max(8,Math.ceil((Math.max(...all,7.1)+.5)*2)/2),Y=v=>p.t+ph*(1-v/max),X=i=>dates.length>1?p.l+pw*i/(dates.length-1):p.l+pw/2;[[0,2.3,'rgba(25,135,84,.07)'],[2.3,4.5,'rgba(255,193,7,.08)'],[4.5,7.1,'rgba(255,126,0,.07)'],[7.1,max,'rgba(220,53,69,.06)']].forEach(([a,b,col])=>{ctx.fillStyle=col;ctx.fillRect(p.l,Y(b),pw,Y(a)-Y(b))});for(let i=0;i<=4;i++){const v=max-max*i/4,py=Y(v);ctx.strokeStyle='#d7e0e6';ctx.beginPath();ctx.moveTo(p.l,py);ctx.lineTo(w-p.r,py);ctx.stroke();ctx.fillStyle='#667784';ctx.font='10px system-ui';ctx.textAlign='right';ctx.fillText(v.toFixed(1),p.l-7,py+3)}series.forEach(([name,vals,col])=>{ctx.strokeStyle=col;ctx.fillStyle=col;ctx.lineWidth=2.4;ctx.beginPath();let started=false;vals.forEach((v,i)=>{if(!Number.isFinite(v))return;const xx=X(i),yy=Y(v);started?ctx.lineTo(xx,yy):(ctx.moveTo(xx,yy),started=true)});ctx.stroke();vals.forEach((v,i)=>{if(!Number.isFinite(v))return;const xx=X(i),yy=Y(v);ctx.beginPath();ctx.arc(xx,yy,4,0,Math.PI*2);ctx.fill();if(name==='สูงสุด'){ctx.font='700 10px system-ui';ctx.textAlign='center';ctx.fillText(v.toFixed(2),xx,Math.max(p.t+9,yy-9))}})});ctx.fillStyle='#667784';ctx.font='10px system-ui';ctx.textAlign='center';dates.forEach((d,i)=>{if(i%Math.max(1,Math.ceil(dates.length/8))===0||i===dates.length-1)ctx.fillText(String(d).slice(8,10)+'/'+String(d).slice(5,7),X(i),h-p.b+20)});ctx.textAlign='left';ctx.font='600 11px system-ui';ctx.fillStyle='#236c93';ctx.fillText('● สูงสุด',p.l,p.t-15);ctx.fillStyle='#d47a23';ctx.fillText('● เฉลี่ย',p.l+76,p.t-15)}
  function summary(dates,maxVals,avgVals,counts){const c=document.getElementById('vibrationTrendChart'),box=c?.closest('.condition-card')?.querySelector('.condition-summary');if(!box)return;const lastMax=[...maxVals].reverse().find(Number.isFinite),lastAvg=[...avgVals].reverse().find(Number.isFinite),allMax=maxVals.filter(Number.isFinite),total=counts.reduce((s,n)=>s+n,0);box.innerHTML=`<span>ล่าสุดสูงสุด: <b>${lastMax==null?'-':lastMax.toFixed(2)+' mm/s'}</b></span><span>ล่าสุดเฉลี่ย: <b>${lastAvg==null?'-':lastAvg.toFixed(2)+' mm/s'}</b></span><span>สูงสุดทั้งหมด: <b>${allMax.length?Math.max(...allMax).toFixed(2)+' mm/s':'-'}</b></span><span>สถานะ: <b>${status(lastMax)}</b></span><span>จำนวนค่า: <b id="vibChecked">${total}</b></span>`}
  function reference(){const c=document.getElementById('vibrationTrendChart'),card=c?.closest('.condition-card');if(!card||card.querySelector('.vib-standard-reference'))return;const n=document.createElement('div');n.className='vib-standard-reference';n.innerHTML='<b>Screening reference:</b> Normal &lt;2.3, Watch 2.3-&lt;4.5, Alert 4.5-&lt;7.1, Danger >=7.1 mm/s RMS <span>(เกณฑ์คัดกรองเบื้องต้น)</span>';c.closest('.chart-wrap')?.before(n)}
  const st=document.createElement('style');st.textContent='.vibration-na{text-align:center!important;color:#9aa8b2!important;font-weight:700}.vib-standard-reference{margin:7px 0 4px;padding:7px 9px;border:1px solid #d6e0e6;border-radius:8px;background:#f7fafc;font-size:10px;color:#526674}#vibrationTrendChart{min-height:285px}';document.head.appendChild(st);
  const old=window.renderConditionTrends;if(typeof old==='function'){const wrap=function(...args){let r;try{r=old.apply(this,args)}catch(e){if(!/vib(Latest|Min|Max|Checked|OK|NG|Rate)/.test(String(e?.message||e)))console.warn('base condition trend failed',e)}setTimeout(draw,0);return r};window.renderConditionTrends=wrap;try{renderConditionTrends=wrap}catch(e){}}
  document.addEventListener('change',e=>{if(['dashChecklist','dashMachine','dashOperator','dashDateFrom','dashDateTo'].includes(e.target?.id))setTimeout(draw,20)});
  const tb=document.getElementById('checklistBody');if(tb)new MutationObserver(()=>setTimeout(configureInputs,0)).observe(tb,{childList:true,subtree:true});
  setTimeout(draw,350);setTimeout(draw,1000);
})();